### ISSUE TITLE
How to solve this error while install?

### ISSUE THREAD

**Issue by yech1990** [annalam/breakfast#4]
```bash
warning: unused variable: `anchor_mm`
  --> src/detect.rs:48:6
   |
48 |  let anchor_mm: usize = args.get_str("--anchor-mm").parse().unwrap();
   |      ^^^^^^^^^
   |
   = note: #[warn(unused_variables)] on by default
   = note: to avoid this warning, consider using `_anchor_mm` instead
error[E0596]: cannot borrow immutable borrowed content `*bam` as mutable
   --> src/detect.rs:304:11
    |
279 | fn dispatch_unaligned_reads_with_frag_signature(bam: &bam::Reader, aligner_in: &mut Write, anchor_len: usize) {
    |                                                      ------------ use `&mut bam::Reader` here to make mutable
...
304 |  for r in bam.records() {
    |           ^^^ cannot borrow as mutable
error[E0596]: cannot borrow immutable borrowed content `*bam` as mutable
   --> src/detect.rs:382:11
    |
380 | fn dispatch_unaligned_reads_with_frag_id(bam: &bam::Reader, aligner_in: &mut Write, anchor_len: usize) {
    |                                               ------------ use `&mut bam::Reader` here to make mutable
381 |  let mut num_reads_sent = 0;
382 |  for r in bam.records() {
    |           ^^^ cannot borrow as mutable
error: aborting due to 2 previous errors

```

**Comment by annalam** [comment]
These errors were caused by changes in the rust-htslib API. I have now updated the code to work with rust-htslib-0.15.0, and Cargo.toml now requires this specific version of rust-htslib. You can try rebuilding the latest version.

**Comment by yech1990** [comment]
@annalam 

Another error...

```bash
error[E0599]: no method named `to_ascii_lowercase` found for type `u8` in the current scope
   --> src/detect.rs:167:69
    |
167 |    junction[k] = if seq[k] == left_grch[k] { seq[k] } else { seq[k].to_ascii_lowercase() };
    |                                                                     ^^^^^^^^^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use std::ascii::AsciiExt;`
error[E0599]: no method named `to_ascii_lowercase` found for type `u8` in the current scope
   --> src/detect.rs:171:72
    |
171 |    junction[k+1] = if seq[k] == right_grch[k] { seq[k] } else { seq[k].to_ascii_lowercase() };
    |                                                                        ^^^^^^^^^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use std::ascii::AsciiExt;`
error: aborting due to 2 previous errors
```

**Comment by yech1990** [comment]
@annalam 

I never write rust before, but It seems that editing these lines will fix the error.

#5

**Comment by annalam** [comment]
The error with to_ascii_lowercase() occurs because you are using an old version of Rust. There was a change in Rust 1.23 that made it unnecessary to include the line "use std::ascii::AsciiExt;" anymore.

Your pull request is ok for making it compile on older versions of Rust.

**Comment by yech1990** [comment]
Thanks you @annalam .
